server:
  port: 8093
spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/restaurant_user_app
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: user-service